openapi: 3.0.3
info:
  title: Parts Unlimited API QVentus
  version: 1.0.0
  description: API for take-home assignment for QVentus
paths:
  /api/common-words/:
    get:
      operationId: common_words_retrieve
      description: Retrieve the 5 most common words in the descriptions of all parts.
      tags:
      - common-words
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonWords'
          description: ''
  /api/parts/:
    get:
      operationId: parts_list
      description: Retrieve a list of parts, optionally filtered by is_active
      parameters:
      - in: query
        name: is_active
        schema:
          type: boolean
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - parts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPartList'
          description: ''
    post:
      operationId: parts_create
      description: Create a new part.
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Part'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Part'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
  /api/parts/{id}/:
    get:
      operationId: parts_retrieve
      description: Retrieve a single part by ID.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    put:
      operationId: parts_update
      description: Update an existing part.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Part'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Part'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    patch:
      operationId: parts_partial_update
      description: Partially update an existing part.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPart'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPart'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPart'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    delete:
      operationId: parts_destroy
      description: Delete an existing part.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    CommonWords:
      type: object
      properties:
        word:
          type: string
        count:
          type: integer
      required:
      - count
      - word
    PaginatedPartList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Part'
    Part:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        links:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
          readOnly: true
        name:
          type: string
          maxLength: 150
        sku:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 1024
        weight_ounces:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        is_active:
          type: boolean
      required:
      - description
      - id
      - links
      - name
      - sku
      - weight_ounces
    PatchedPart:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        links:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
          readOnly: true
        name:
          type: string
          maxLength: 150
        sku:
          type: string
          maxLength: 30
        description:
          type: string
          maxLength: 1024
        weight_ounces:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        is_active:
          type: boolean
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
